# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(318, 285)
        MainWindow.setStyleSheet("background-color: #D9F5FC\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.only_num = QtWidgets.QCheckBox(self.centralwidget)
        self.only_num.setGeometry(QtCore.QRect(10, 110, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.only_num.setFont(font)
        self.only_num.setObjectName("only_num")
        self.only_liters = QtWidgets.QCheckBox(self.centralwidget)
        self.only_liters.setGeometry(QtCore.QRect(10, 140, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.only_liters.setFont(font)
        self.only_liters.setObjectName("only_liters")
        self.gen_password = QtWidgets.QLabel(self.centralwidget)
        self.gen_password.setGeometry(QtCore.QRect(60, 10, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.gen_password.setFont(font)
        self.gen_password.setStyleSheet("border-radius: 5px;\n"
"border: 2px solid black\n"
"")
        self.gen_password.setObjectName("gen_password")
        self.results = QtWidgets.QLabel(self.centralwidget)
        self.results.setGeometry(QtCore.QRect(100, 70, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.results.setFont(font)
        self.results.setObjectName("results")
        self.generate = QtWidgets.QPushButton(self.centralwidget)
        self.generate.setGeometry(QtCore.QRect(100, 200, 101, 21))
        self.generate.setStyleSheet("border-radius: 5px;\n"
"background: #ffffff;\n"
"border: 1px solid #141c21")
        self.generate.setObjectName("generate")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 318, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.only_num.setText(_translate("MainWindow", " Тільки цифри"))
        self.only_liters.setText(_translate("MainWindow", "Тільки букви"))
        self.gen_password.setText(_translate("MainWindow", "Генератор паролів"))
        self.results.setText(_translate("MainWindow", "*Результат*"))
        self.generate.setText(_translate("MainWindow", "Згенерувати"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
